// <auto-generated />
namespace Desafio.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addforegkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addforegkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202009112223035_addforegkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
